name: Update playlist

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  playlist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Update playlist
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_USER_CREDENTIALS: ${{ secrets.SPOTIFY_USER_CREDENTIALS }}
          SPOTIFY_PLAYLIST: ${{ secrets.SPOTIFY_PLAYLIST }}
        run: bundle exec ruby update_playlist.rb
